import type { Metadata } from 'next'
import { Roboto, Open_Sans } from 'next/font/google'
import '../css/globals.css'
import { ThemeProvider } from '@/providers/theme-provider'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
  subsets: ['latin'],
})

const open = Open_Sans({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-open',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.variable} ${open.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableColorScheme
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
